basic noop ruby script

diff --git a/autotune-build b/autotune-build
--- a/autotune-build
+++ b/autotune-build
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-BUILD_COMMAND='bundle exec middleman build'
+BUILD_COMMAND="bundle exec ruby test.rb"
 DEPLOY_COMMAND=''
 INPUT_DATA=$(</dev/stdin)
 SAVE_DATA_TO=data/autotune.json
@@ -20,8 +20,14 @@ printenv
 
 echo ''
 echo 'Building the blueprint:'
-exec $BUILD_COMMAND
+$BUILD_COMMAND
 
-echo ''
-echo 'Deploying the build:'
-exec $DEPLOY_COMMAND
+if [ $? -eq 0 ]; then
+  echo ''
+  echo 'Deploying the build:'
+  $DEPLOY_COMMAND
+else
+  echo ''
+  echo 'Build failed'
+  exit 1
+fi
